/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.archive.mainwindow.monitor.xml -i mainwindow.h -a monitorAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MONITORADAPTOR_H
#define MONITORADAPTOR_H

#include "mainwindow.h"

#include <QtCore/QObject>
#include <QtDBus/QtDBus>

QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.archive.mainwindow.monitor
 */
class MonitorAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.archive.mainwindow.monitor")
    Q_CLASSINFO("D-Bus Introspection", ""
                "  <interface name=\"com.archive.mainwindow.monitor\">\n"
                "    <method name=\"onSubWindowActionFinished\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"i\" name=\"mode\"/>\n"
                "      <arg direction=\"in\" type=\"x\" name=\"pid\"/>\n"
                "      <arg direction=\"in\" type=\"as\" name=\"urls\"/>\n"
                "    </method>\n"
                "    <method name=\"popUpChangedDialog\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"x\" name=\"pid\"/>\n"
                "    </method>\n"
                "    <method name=\"createSubWindow\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"as\" name=\"urls\"/>\n"
                "    </method>\n"
                "  </interface>\n"
                "")
public:
    MonitorAdaptor(QObject *parent);
    virtual ~MonitorAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool createSubWindow(const QStringList &urls);
    bool onSubWindowActionFinished(int mode, qlonglong pid, const QStringList &urls);
    bool popUpChangedDialog(qlonglong pid);
Q_SIGNALS: // SIGNALS
};

#endif
