#ifndef READONLYLIBARCHIVEPLUGIN_GLOBAL_H
#define READONLYLIBARCHIVEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(READONLYLIBARCHIVEPLUGIN_LIBRARY)
#  define READONLYLIBARCHIVEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define READONLYLIBARCHIVEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // READONLYLIBARCHIVEPLUGIN_GLOBAL_H
